    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    hostname: client1
spring:
  application:
    name: client1
girl:
  age:dev18
env:
  dev
